Made test cases for 1-my_list.py
===========================================
===========================================

test case
>>> MyList = __import__('1-my_list').MyList
>>>
===========================================
===========================================

test case

>>> az_custom = MyList()
>>> az_custom.append(1)
>>> az_custom.append(4)
>>> az_custom.append(2)
>>> az_custom.append(3)
>>> az_custom.append(5)
>>> print(az_custom)
[1, 4, 2, 3, 5]
>>> az_custom.print_sorted()
[1, 2, 3, 4, 5]
>>> print(az_custom)
[1, 4, 2, 3, 5]
>>>

=============================================
=============================================

test case

>>> az = [1, 100, 10]
>>> az_custom = MyList(az)
>>> az_custom.print_sorted()
[1, 10 100]
>>>

==============================================
==============================================

stack or list with no element
>>> az = []
>>> az_custom = MyList(az)
>>> az_custom.print_sorted()
[]
>>>

===============================================
=============================================== 

test case

>>> az_custom = MyList()
>>> az_custom.append(10)
>>> az_custom.print_sorted()
[10]
>>> print(az_custom)
[10]
>>>

===============================================
===============================================

test case of inheritance of super class
>>> az_custom = [9, -1, 33]
>>> az_custom.print_sorted()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'print_sorted'
>>>

================================================
================================================

test case of positive and negative integers

>>> MyList = __import__('1-my_list').MyList
>>> az_custom = MyList()
>>> az_custom.append(9)
>>> az_custom.append(-2)
>>> az_custom.append(0)
>>> az_custom.append(-9)
>>> az_custom.append(2)
>>> az_custom.print_sorted()
[-9, -2, 0, 2, 9]
>>>

===============================================
===============================================

test case

>>> custom_bj = MyList()

>>> custom_bj.append(adfa)
Traceback (most recent call last):
    ...
NameError: name 'adfa' is not defined
